baseurl = "https://ivalab.github.io/VisNav/public"
baseURL = "https://ivalab.github.io/VisNav/public"
title = "VisNav Research"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
defaultContentLanguage = "en-us"
disqusShortname = ""
googleAnalytics = ""

[params]
  style = "sea"
  title = "IVALab:VisNav"
  description = "Research efforts related to vision-in-the-loop navigation." 
  copyright = ""
  support = "Research supported in part by National Science Foundation.  Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation."
  sidebarAbout = ["Research efforts related to egocentric, perception-space, visual navigation."]


  [[params.grants]]
  grantee = "NSF"
  award = "1849333"
  url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1849333&HistoricalAwards=false"

  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = false

  [[params.navlinks]]
  name = "Robots"
  url  = "robots/"
  home = false

  [[params.navlinks]]
  name = "Research"
  url  = "research/"
  home = true

  [params.social]
  github  = "https://github.com/ivalab"
  github2  = "https://github.com/ivaROS"
  youtube = "https://www.youtube.com/channel/UC-YbwwjK5GE1YjVolgNe5Kg/"
